// src/App.svelte
<script>
  import Rating from './lib/Rating.svelte';
  import ThankYou from './lib/ThankYou.svelte';

  let submit = false;
  let rate = 0;
</script>

<div class="bg-very-dark-blue grid h-screen w-screen place-items-center">
  {#if !submit}
    <Rating bind:submit bind:rate />
  {:else}
    <ThankYou {rate} />
  {/if}
</div>

// src/App.jsx
import { useState } from 'react';
import Rating from './lib/Rating';
import ThankYou from './lib/ThankYou';

export default function App() {
    const [thankYou, setThankYou] = useState(false);
    const [ratings, setRatings] = useState(0);

    function updateThankYou() {
        setThankYou(true);
    }

    function updateRatings(r) {
        setRatings(r);
    }

    return (
        <main class="wfa grid h-screen place-items-center">
            {thankYou ? (
                <ThankYou ratings={ratings} />
            ) : (
                <Rating
                    ratings={ratings}
                    updateThankYou={updateThankYou}
                    updateRatings={updateRatings}
                />
            )}
        </main>
    );
}
